# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatbotSerializer',
            new_name='Chatbot',
        ),
    ]
