# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_auto_20180909_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='date_time',
            new_name='send_date_time',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='user',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='received_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SendTo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SendFrom', to=settings.AUTH_USER_MODEL),
        ),
    ]
