# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20180909_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='send_date_time',
            new_name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='received_date_time',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='message_reference_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
