# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20180912_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='message_reference_id',
        ),
    ]
